PacientesApp/Models/EnumEspecializacao.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PacientesApp.Models
{
    public enum EnumEspecializacao
    {
        Anestesiologia,
        Cancerologia,
        Cardiologia,
        Cirurgia,
        Endocrinologia,
        Endoscopia,
        Gastroenterologia,
        Ginecologia,
        Infectologia,
        Nefrologia,
        Neurocirurgia,
        Neurologia,
        Oftalmologia
    }  
}

PacientesApp/Models/ErrorViewModel.cs
using System;

namespace PacientesApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PacientesApp/Models/Medico.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace PacientesApp.Models
{
    public class Medico
    {
        [HiddenInput]
        public int Codigo { get; set; }

        [Display(Name = "Nome")]
        [MaxLength(30), Required]
        public string Nome { get; set; }

        [Display(Name = "Sobrenome")]
        [MaxLength(60), Required]
        public string Sobrenome { get; set; }

        [Display(Name = "Data Nascimento")]
        [DataType(DataType.Date), Required]
        public DateTime DataNascimento { get; set; }

        [Display(Name = "CRM")]
        [MaxLength(12), Required]
        public string CRM { get; set; }

        [Display(Name = "Ano de formacao")]
        [Required]
        public int AnoFormacao { get; set; }

        [Display(Name = "Especializacao")]
        [Required]
        public EnumEspecializacao Especializacao { get; set; }

    }
}

PacientesApp/Models/Paciente.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace PacientesApp.Models
{
    public class Paciente 
    {
        [HiddenInput]
        public int Codigo { get; set; }

        [Display(Name = "Nome")]
        public string Nome { get; set; }

        [Display(Name = "Sobrenome")]
        public string Sobrenome { get; set; }

        [Display(Name = "Data Nascimento")]
        [DataType(DataType.Date)]
        public DateTime DataNascimento { get; set; }

        [Display(Name = "CRM")]
        public int CRM { get; set; }

        [Display(Name = "Ano de formacao")]
        public int AnoFormacao { get; set; }

        [Display(Name = "Especializacao")]
        public string Especializacao { get; set; }

    }
}

PacientesApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PacientesApp.Models;

namespace PacientesApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PacientesApp/Controllers/MedicoController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using PacientesApp.Models;

namespace PacientesApp.Controllers
{
    [Route("medico")]
    public class MedicoController : Controller
    {
        private static List<Medico> _banco = new List<Medico>();

        public IActionResult Index()
        {
            return View(_banco);
        }

        [HttpPost]
        public IActionResult Remover(int id)
        {
            _banco.RemoveAt(_banco.FindIndex(x => x.Codigo == id));
            return RedirectToAction("Index");
        }

        [HttpPost("editar")]
        public IActionResult Editar(Medico paciente)
        {
            _banco[_banco.FindIndex(x => x.Codigo == paciente.Codigo)] = paciente;
            return RedirectToAction("Index");
        }

        [HttpGet("editar")]
        public IActionResult Editar(int id)
        {
            var paciente = _banco.Find(x => x.Codigo == id);
            return View(paciente);
        }


        [HttpGet("cadastrar")]
        public IActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost("cadastrar")]
        public IActionResult Cadastrar(Medico paciente)
        {
            if (_banco.Any())
            {
                paciente.Codigo = _banco[_banco.Count - 1].Codigo + 1;
            }
            else
            {
                paciente.Codigo = 1;
            }
            _banco.Add(paciente);
            return RedirectToAction("Index");
        }

        [HttpPost("especializacao")]
        public IActionResult FiltrarEspecializacao(string especializacao)
        {
            _banco = _banco.Where(x => x.Especializacao.ToString().ToLower() == especializacao.ToLower()).ToList();
            return RedirectToAction("Index");
        }
    }
}

PacientesApp/Controllers/PacienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PacientesApp.Models;

namespace PacientesApp.Controllers
{
    public class PacienteController : Controller
    {
        private static List<Paciente> _banco = new List<Paciente>();

        public IActionResult Index()
        {
            return View(_banco);
        }

        [HttpPost]
        public IActionResult Remover(int id)
        {
            _banco.RemoveAt(_banco.FindIndex(x => x.Codigo == id));
            TempData["msg"] = "Paciente removido";
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Editar(Paciente paciente)
        {
            _banco[_banco.FindIndex(x => x.Codigo == paciente.Codigo)] = paciente;
            TempData["msg"] = "Paciente atualizado com sucesso";
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Editar(int id)
        {
            var paciente = _banco.Find(x => x.Codigo == id);
            return View(paciente);
        }


        [HttpGet]
        public IActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Cadastrar(Paciente paciente)
        {
            if (_banco.Any())
            {
                paciente.Codigo = _banco[_banco.Count - 1].Codigo + 1;
            }
            else
            {
                paciente.Codigo = 1;
            }
            _banco.Add(paciente);
            TempData["msg"] = "Paciente cadastrado";
            return RedirectToAction("Cadastrar");
        }
    }
}

PacientesApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <titulo texto="Bem-vindo ao MedApp, ferramenta de gerenciamento de cadastros médicos"></titulo>
</div>

PacientesApp/Views/Medico/Cadastrar.cshtml
@model Medico

@{

    ViewData["Nome"] = "Cadastrar";
}

<titulo texto="Cadastro"></titulo>

<form asp-controller="medico" asp-action="cadastrar" >
    <partial name="_Form" />
    <input type="submit" value="Cadastrar" class="btn btn-outline-primary" />
</form>

PacientesApp/Views/Medico/Editar.cshtml
@model Medico

@{ //viewdata?
    ViewData["Nome"] = "Editar";
}

<titulo texto="Editar"></titulo>

<form asp-controller="medico" asp-action="editar">
    <input asp-for="Codigo" />

    <partial name="_Form" />

    <input type="submit" value="Editar" class="btn btn-outline-primary" />
    <a asp-controller="paciente" asp-action="index" class="btn btn-outline-dark">Cancelar</a>
</form>

PacientesApp/Views/Medico/Index.cshtml
@model IList<Medico>

@{
    ViewData["Nome"] = "Index";
}

<titulo texto="Médicos"></titulo>

<form asp-controller="medico" asp-action="especializacao">
    <div class="form-group">
        <label>Filtrar por especialização</label>
        <input class="form-control" name="especializacao" />
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-sm btn-outline-primary">Filtrar</button>
    </div>
</form>

    <table class="table">
        <tr>

            <th>Codigo</th>
            <th>Nome</th>
            <th>Sobrenome</th>
            <th>Data Nascimento</th>
            <th>CRM</th>
            <th>Ano da formação</th>
            <th>Especialização</th>

        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Codigo</td>
                <td>@item.Nome</td>
                <td>@item.Sobrenome</td>
                <td>@item.DataNascimento</td>
                <td>@item.CRM</td>
                <td>@item.AnoFormacao</td>
                <td>@item.Especializacao</td>

                <td>
                    <a asp-action="editar" class="btn btn-sm btn-outline-primary" asp-route-id="@item.Codigo">Editar</a>
                    <button onclick="Codigo.value= @item.Codigo" type="button" class="btn btn-sm btn-outline-danger" data-toggle="modal" data-target="#exampleModal">
                        Excluir
                    </button>
                </td>
            </tr>
        }
    </table>
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Remoção de registro</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true"></span>
                    </button>
                </div>
                <div class="modal-body">
                    Deseja realmente excluir este registro?
                </div>
                <div class="modal-footer">
                    <form asp-action="remover" asp-controller="medico" method="post">
                        <input type="hidden" name="id" id="Codigo" />
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Não</button>
                        <button type="submit" class="btn btn-danger">Sim</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

PacientesApp/Views/Medico/_Form.cshtml
@model Medico

<div class="form-group">
    <label asp-for="Nome"></label>
    <input asp-for="Nome" class="form-control" />

</div>

<div class="form-group">
    <label asp-for="Sobrenome"></label>
    <input asp-for="Sobrenome" class="form-control" />

</div>

<div class="form-group">
    <label asp-for="DataNascimento"></label>
    <input asp-for="DataNascimento" class="form-control" />

</div>

<div class="form-group">
    <label asp-for="CRM"></label>
    <input asp-for="CRM" class="form-control" />

</div>

<div class="form-group">
    <label asp-for="AnoFormacao"></label>
    <input asp-for="AnoFormacao" class="form-control" />

</div>

<div class="form-group">
    <label asp-for="Especializacao"></label>
    <select asp-for="Especializacao" class="form-control" asp-items="@Html.GetEnumSelectList<EnumEspecializacao>()">
        <option>Selecione</option>
    </select>

</div>

PacientesApp/Views/Paciente/Cadastrar.cshtml
@model Paciente

@{

    ViewData["Nome"] = "Cadastrar";
}

<h1>Cadastrar</h1>
<a asp-action="Index" asp-controller="Paciente">Pacientes</a>

<mensagem texto="@TempData["msg"]" class="alert alert-danger"></mensagem>

<form asp-action="cadastrar" asp-controller="paciente">
    <partial name="_Form" />

    <input type="submit" value="Cadastrar" class="btn btn-outline-primary" />
    <a asp-action="index" asp-controller="paciente" class="btn btn-outline-dark">Pacientes</a>
</form>

PacientesApp/Views/Paciente/Editar.cshtml
@model Paciente

@{ //viewdata?
    ViewData["Nome"] = "Editar";
}

<h1>Editar</h1>

<form asp-controller="paciente" asp-action="editar">
    <input asp-for="Codigo" />

    <partial name="_Form" />

    <input type="submit" value="Editar" class="btn btn-outline-primary" />
    <a asp-controller="paciente" asp-action="index" class="btn btn-outline-dark">Cancelar</a>
</form>

PacientesApp/Views/Paciente/Index.cshtml
@model IList<Paciente>

@{
    ViewData["Nome"] = "Index";
}

<h1>Pacientes</h1>

<mensagem texto="@TempData["msg"]" class="alert alert-success"></mensagem>

<a asp-action="cadastrar" asp-controller="paciente">Cadastrar</a>
<table class="table">
    <tr>

        <th>Codigo</th>
        <th>Nome</th>
        <th>Sobrenome</th>
        <th>Data Nascimento</th>
        <th>CRM</th>
        <th>Ano da formação</th>
        <th>Especialização</th>

    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Codigo</td>
            <td>@item.Nome</td>
            <td>@item.Sobrenome</td>
            <td>@item.DataNascimento</td>
            <td>@item.CRM</td>
            <td>@item.AnoFormacao</td>
            <td>@item.Especializacao</td>

            <td>
                <a asp-action="editar" class="btn btn-sm btn-outline-primary" asp-route-id="@item.Codigo">Editar</a>
                <button onclick="pacienteId.value= @item.Codigo" type="button" class="btn btn-sm btn-outline-danger" data-toggle="modal" data-target="#exampleModal">
                    Excluir
                </button>
            </td>
        </tr>
    }
</table>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">Confirmação</span>
                </button>
            </div>
            <div class="modal-body">
                Deseja realmente excluir o paciente?
            </div>
            <div class="modal-footer">
                <form asp-action="remover" asp-controller="paciente">
                    <input type="hidden" name="id" id="pacienteId" />
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Não</button>
                    <button type="submit" class="btn btn-danger">Sim</button>
                </form>
            </div>
        </div>
    </div>
</div>

PacientesApp/Views/Paciente/_Form.cshtml
@model Paciente

<div class="form-group">
    <label asp-for="Nome"></label>
    <input asp-for="Nome" class="form-control" />

</div>

<div class="form-group">
    <label asp-for="Sobrenome"></label>
    <input asp-for="Sobrenome" class="form-control" />

</div>

<div class="form-group">
    <label asp-for="DataNascimento"></label>
    <input asp-for="DataNascimento" class="form-control" />

</div>

<div class="form-group">
    <label asp-for="CRM"></label>
    <input asp-for="CRM" class="form-control" />

</div>

<div class="form-group">
    <label asp-for="AnoFormacao"></label>
    <input asp-for="AnoFormacao" class="form-control" />

</div>

<div class="form-group">
    <label asp-for="Especializacao"></label>
    <input asp-for="Especializacao" class="form-control" />

</div>

PacientesApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>MedApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MedApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="medico" asp-action="index">Index</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="medico" asp-action="cadastrar" method="get">Formulário de cadastro</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MedApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>